### ISSUE TITLE
Facebook Integration

### ISSUE THREAD

**Issue by dbalduini** [wejs/we-plugin-event#35]
Nowadays, everyone is using Facebook as the main tool for event management.
I think it would be a great differential if you guys have a feature for automatically creating a facebook event after registering an event in the dashboard.

**Comment by albertosouza** [comment]
Ref: https://developers.facebook.com/docs/graph-api/reference/event

**Comment by albertosouza** [comment]
@dbalduini  I dont know if is possible but i think:

1- after create one event in portal allow to create one event in facebook with portal event data (banner, logo, name ... )
2- after create one cfnews (news) automaticaly share it in facebook
3- On change something in event automaticaly change facebook event data

**Comment by dbalduini** [comment]
It is not possible to create events on facebook anymore. Sorry for the inconvenience.

Quote:
> the create_event permission is no longer available.

Try:

```
POST https://graph.facebook.com/v1.0/me/events?access_token=<my_token>

name=This+is+a+test+event&start_time=2014-03-01T13%3A00%3A00-0800
```

```
{
  "error": {
    "message": "(#12) events management API is deprecated for versions v2.0 and higher",
    "type": "OAuthException",
    "code": 12,
    "fbtrace_id": "CQDNr1J9sAV"
  }
}
```

**Comment by dbalduini** [comment]
Btw, the idea of sharing the event is awesome.

**Comment by albertosouza** [comment]
Ok, thanks.

For now "login with facebook" plugin will help a lot user registrations and will be something simple to implement with https://github.com/jaredhanson/passport-facebook
